# config.yml
# vim: ft=yml

#   __|    \    _ \  |      _ \   __| __ __| __ __|
#  (      _ \     /  |     (   | (_ |    |      |
# \___| _/  _\ _|_\ ____| \___/ \___|   _|     _|


# ----------------
# General Settings
# ----------------
# What to do when opening Lazygit outside of a git repo.
# - 'prompt': (default) ask whether to initialize a new repo or open in the most recent repo
# - 'create': initialize a new repo
# - 'skip': open most recent repo
# - 'quit': exit Lazygit
notARepository: 'skip'


# ----------------------
# Config relating to git
# ----------------------
git:
  # If not "none", lazygit will automatically forward branches to their upstream after fetching.
  # Applies to branches that are not the currently checked out branch, and only to those that are strictly behind their upstream (as opposed to diverged).
  # Possible values: 'none' | 'onlyMainBranches' | 'allBranches'
  autoForwardBranches: none

